/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    posts: Post;
    brands: Brand;
    categories: Category;
    contacts: Contact;
    footers: Footer;
    pages: Page;
    products: Product;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    contacts: ContactsSelect<false> | ContactsSelect<true>;
    footers: FootersSelect<false> | FootersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Quản trị viên: toàn quyền. Biên tập viên: quản lý nội dung nhưng không quản lý người dùng.
   */
  role?: ('admin' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  /**
   * Mô tả ngắn hiển thị trong danh sách bài viết
   */
  excerpt?: string | null;
  /**
   * Ảnh chính hiển thị ở đầu bài viết
   */
  featuredImage?: (number | null) | Media;
  /**
   * Nội dung chính với văn bản và hình ảnh
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author: number | User;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Bài viết đã xuất bản sẽ hiển thị công khai
   */
  published?: boolean | null;
  publishedAt?: string | null;
  metadata?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  name: string;
  slug: string;
  logo?: (number | null) | Media;
  website?: string | null;
  description?: string | null;
  country?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  /**
   * Dòng sản phẩm cha (không bắt buộc)
   */
  parent?: (number | null) | Category;
  order?: number | null;
  image?: (number | null) | Media;
  metadata?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts".
 */
export interface Contact {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  company?: string | null;
  message: string;
  product?: (number | null) | Product;
  status?: ('new' | 'contacted' | 'closed') | null;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  slug: string;
  sku?: string | null;
  brand?: (number | null) | Brand;
  category?: (number | null) | Category;
  shortDescription?: string | null;
  /**
   * Ứng dụng của sản phẩm (VD: Nhà máy, tòa nhà, hệ thống điện dân dụng)
   */
  applications?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  specs?:
    | {
        key?: string | null;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Hình ảnh sản phẩm (sử dụng R2 upload)
   */
  images?: (number | Media)[] | null;
  catalog?: (number | null) | Media;
  relatedProducts?: (number | Product)[] | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  published?: boolean | null;
  publishedAt?: string | null;
  stock?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Quản lý nội dung và cấu hình footer
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footers".
 */
export interface Footer {
  id: number;
  /**
   * Tên nội bộ cho cấu hình footer này
   */
  name: string;
  /**
   * Thêm lợi ích/tính năng hiển thị trong footer (VD: "Bán hàng chính hãng", "Giao hàng tận nơi")
   */
  benefits?:
    | {
        /**
         * Icon cho lợi ích này
         */
        icon?: (number | null) | Media;
        /**
         * Văn bản lợi ích (VD: "BÁN HÀNG CHÍNH HÃNG - GIAO HÀNG TẬN NƠI - TƯ VẤN MIỄN PHÍ")
         */
        text: string;
        id?: string | null;
      }[]
    | null;
  columns?: {
    addressColumn?: {
      /**
       * Tiêu đề cột
       */
      heading?: string | null;
      /**
       * Tên công ty (VD: "Công ty Cổ phần Kỹ thuật Dtech")
       */
      companyName?: string | null;
      /**
       * Địa chỉ đầy đủ
       */
      address?: string | null;
      /**
       * URL nhúng Google Maps (không bắt buộc)
       */
      mapUrl?: string | null;
    };
    contactColumn?: {
      /**
       * Tiêu đề cột
       */
      heading?: string | null;
      /**
       * Danh sách người liên hệ
       */
      contacts?:
        | {
            /**
             * Tên người liên hệ (VD: "Ms. Trang", "Mr. Hùng")
             */
            name: string;
            /**
             * Số điện thoại
             */
            phone?: string | null;
            /**
             * Số Zalo (nếu khác số điện thoại)
             */
            zalo?: string | null;
            /**
             * Địa chỉ email
             */
            email?: string | null;
            id?: string | null;
          }[]
        | null;
      /**
       * Số hotline/điện thoại chung
       */
      generalPhone?: string | null;
      /**
       * Địa chỉ email chung
       */
      generalEmail?: string | null;
    };
    servicesColumn?: {
      /**
       * Tiêu đề cột
       */
      heading?: string | null;
      /**
       * Mô tả dịch vụ hoặc danh sách
       */
      content?: {
        root: {
          type: string;
          children: {
            type: any;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
      /**
       * Thêm liên kết nhanh đến dịch vụ hoặc trang
       */
      links?:
        | {
            text: string;
            url: string;
            id?: string | null;
          }[]
        | null;
    };
  };
  bottomContent?: {
    /**
     * Văn bản bản quyền
     */
    copyrightText?: string | null;
    /**
     * Liên kết cho chính sách bảo mật, điều khoản, v.v.
     */
    additionalLinks?:
      | {
          text: string;
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  socialMedia?: {
    /**
     * URL trang Facebook
     */
    facebook?: string | null;
    /**
     * URL Zalo
     */
    zalo?: string | null;
    /**
     * URL kênh YouTube
     */
    youtube?: string | null;
    /**
     * URL LinkedIn
     */
    linkedin?: string | null;
  };
  /**
   * Đặt footer này là đang hoạt động
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  /**
   * Chọn mẫu bố cục cho trang này
   */
  layout: 'home' | 'about' | 'contact' | 'standard';
  seo?: {
    /**
     * Tiêu đề SEO (tối đa 60 ký tự). Để trống để sử dụng tiêu đề trang.
     */
    metaTitle?: string | null;
    /**
     * Mô tả SEO cho công cụ tìm kiếm (tối đa 160 ký tự)
     */
    metaDescription?: string | null;
    /**
     * Từ khóa SEO, phân cách bằng dấu phẩy
     */
    metaKeywords?: string | null;
    /**
     * Ảnh chia sẻ mạng xã hội (Open Graph)
     */
    ogImage?: (number | null) | Media;
    /**
     * Tiêu đề mạng xã hội. Để trống để sử dụng tiêu đề trang.
     */
    ogTitle?: string | null;
    /**
     * Mô tả mạng xã hội. Để trống để sử dụng mô tả SEO.
     */
    ogDescription?: string | null;
  };
  hero?: {
    /**
     * Hiển thị phần hero trên trang này
     */
    showHero?: boolean | null;
    /**
     * Tiêu đề chính trong phần hero
     */
    title?: string | null;
    /**
     * Tiêu đề phụ trong phần hero
     */
    subtitle?: string | null;
    /**
     * Văn bản mô tả hero
     */
    description?: string | null;
    /**
     * Ảnh nền hero
     */
    image?: (number | null) | Media;
    /**
     * Văn bản nút kêu gọi hành động
     */
    buttonText?: string | null;
    /**
     * URL nút kêu gọi hành động
     */
    buttonLink?: string | null;
  };
  /**
   * Chọn dòng sản phẩm để hiển thị trên trang này
   */
  featuredCategories?: (number | Category)[] | null;
  /**
   * Nội dung chính (văn bản định dạng)
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Thêm các phần nội dung động vào trang này
   */
  sections?:
    | (
        | {
            heading: string;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            backgroundColor?: ('white' | 'gray' | 'dark') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textSection';
          }
        | {
            heading?: string | null;
            images: {
              image: number | Media;
              caption?: string | null;
              id?: string | null;
            }[];
            columns?: ('2' | '3' | '4') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageGallery';
          }
        | {
            heading?: string | null;
            /**
             * URL YouTube hoặc Vimeo
             */
            videoUrl: string;
            description?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'videoSection';
          }
        | {
            heading: string;
            description?: string | null;
            buttonText: string;
            buttonLink: string;
            backgroundColor?: ('primary' | 'secondary' | 'dark') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaSection';
          }
        | {
            heading: string;
            description?: string | null;
            /**
             * Chọn sản phẩm để hiển thị
             */
            products?: (number | Product)[] | null;
            displayStyle?: ('grid' | 'carousel' | 'list') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'productsSection';
          }
        | {
            /**
             * Nhãn nội bộ cho khối này
             */
            label: string;
            /**
             * Mã HTML tùy chỉnh
             */
            html: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'customHTML';
          }
      )[]
    | null;
  published?: boolean | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'contacts';
        value: number | Contact;
      } | null)
    | ({
        relationTo: 'footers';
        value: number | Footer;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  content?: T;
  author?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  published?: T;
  publishedAt?: T;
  metadata?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  website?: T;
  description?: T;
  country?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  parent?: T;
  order?: T;
  image?: T;
  metadata?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts_select".
 */
export interface ContactsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  company?: T;
  message?: T;
  product?: T;
  status?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footers_select".
 */
export interface FootersSelect<T extends boolean = true> {
  name?: T;
  benefits?:
    | T
    | {
        icon?: T;
        text?: T;
        id?: T;
      };
  columns?:
    | T
    | {
        addressColumn?:
          | T
          | {
              heading?: T;
              companyName?: T;
              address?: T;
              mapUrl?: T;
            };
        contactColumn?:
          | T
          | {
              heading?: T;
              contacts?:
                | T
                | {
                    name?: T;
                    phone?: T;
                    zalo?: T;
                    email?: T;
                    id?: T;
                  };
              generalPhone?: T;
              generalEmail?: T;
            };
        servicesColumn?:
          | T
          | {
              heading?: T;
              content?: T;
              links?:
                | T
                | {
                    text?: T;
                    url?: T;
                    id?: T;
                  };
            };
      };
  bottomContent?:
    | T
    | {
        copyrightText?: T;
        additionalLinks?:
          | T
          | {
              text?: T;
              url?: T;
              id?: T;
            };
      };
  socialMedia?:
    | T
    | {
        facebook?: T;
        zalo?: T;
        youtube?: T;
        linkedin?: T;
      };
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaKeywords?: T;
        ogImage?: T;
        ogTitle?: T;
        ogDescription?: T;
      };
  hero?:
    | T
    | {
        showHero?: T;
        title?: T;
        subtitle?: T;
        description?: T;
        image?: T;
        buttonText?: T;
        buttonLink?: T;
      };
  featuredCategories?: T;
  content?: T;
  sections?:
    | T
    | {
        textSection?:
          | T
          | {
              heading?: T;
              content?: T;
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
        imageGallery?:
          | T
          | {
              heading?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              columns?: T;
              id?: T;
              blockName?: T;
            };
        videoSection?:
          | T
          | {
              heading?: T;
              videoUrl?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        ctaSection?:
          | T
          | {
              heading?: T;
              description?: T;
              buttonText?: T;
              buttonLink?: T;
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
        productsSection?:
          | T
          | {
              heading?: T;
              description?: T;
              products?: T;
              displayStyle?: T;
              id?: T;
              blockName?: T;
            };
        customHTML?:
          | T
          | {
              label?: T;
              html?: T;
              id?: T;
              blockName?: T;
            };
      };
  published?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  sku?: T;
  brand?: T;
  category?: T;
  shortDescription?: T;
  applications?: T;
  description?: T;
  specs?:
    | T
    | {
        key?: T;
        value?: T;
        id?: T;
      };
  images?: T;
  catalog?: T;
  relatedProducts?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  published?: T;
  publishedAt?: T;
  stock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}