/**
 * Comprehensive Mock Data for DTech Vietnam
 * Based on dtech.vn structure for development/testing
 */

import type { Media, Category, Brand, Product, Post, Page, Serial } from '@/app/types';

// ==================== MEDIA ====================
export const MOCK_MEDIA: Media[] = [
  {
    id: 'media-1',
    alt: 'LS Breaker',
    url: '/images/products/ls-breaker.jpg',
    filename: 'ls-breaker.jpg',
    mimeType: 'image/jpeg',
    filesize: 125000,
    width: 800,
    height: 600,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'media-2',
    alt: 'Mitsubishi Inverter',
    url: '/images/products/mitsubishi-inverter.jpg',
    filename: 'mitsubishi-inverter.jpg',
    mimeType: 'image/jpeg',
    filesize: 145000,
    width: 800,
    height: 600,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'media-3',
    alt: 'Schneider Contactor',
    url: '/images/products/schneider-contactor.jpg',
    filename: 'schneider-contactor.jpg',
    mimeType: 'image/jpeg',
    filesize: 135000,
    width: 800,
    height: 600,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'media-4',
    alt: 'LS Logo',
    url: '/images/brands/ls-logo.png',
    filename: 'ls-logo.png',
    mimeType: 'image/png',
    filesize: 25000,
    width: 200,
    height: 100,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'media-5',
    alt: 'Mitsubishi Logo',
    url: '/images/brands/mitsubishi-logo.png',
    filename: 'mitsubishi-logo.png',
    mimeType: 'image/png',
    filesize: 28000,
    width: 200,
    height: 100,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// ==================== BRANDS ====================
export const MOCK_BRANDS: Brand[] = [
  {
    id: 'brand-1',
    name: 'LS Electric',
    slug: 'ls-electric',
    logo: MOCK_MEDIA[3],
    description: 'Tập đoàn LS Electric (Hàn Quốc) - Nhà sản xuất thiết bị điện hàng đầu',
    website: 'https://www.ls-electric.com',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'brand-2',
    name: 'Mitsubishi Electric',
    slug: 'mitsubishi-electric',
    logo: MOCK_MEDIA[4],
    description: 'Mitsubishi Electric (Nhật Bản) - Công nghệ tự động hóa tiên tiến',
    website: 'https://www.mitsubishielectric.com',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'brand-3',
    name: 'Schneider Electric',
    slug: 'schneider-electric',
    description: 'Schneider Electric (Pháp) - Giải pháp quản lý năng lượng',
    website: 'https://www.se.com',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'brand-4',
    name: 'ABB',
    slug: 'abb',
    description: 'ABB (Thụy Sĩ) - Công nghệ tự động hóa và điện',
    website: 'https://www.abb.com',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'brand-5',
    name: 'Siemens',
    slug: 'siemens',
    description: 'Siemens (Đức) - Giải pháp tự động hóa công nghiệp',
    website: 'https://www.siemens.com',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'brand-6',
    name: 'CHINT',
    slug: 'chint',
    description: 'CHINT Electric (Trung Quốc) - Thiết bị điện giá cạnh tranh',
    website: 'https://www.chint.com',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'brand-7',
    name: 'Fuji Electric',
    slug: 'fuji-electric',
    description: 'Fuji Electric (Nhật Bản) - Thiết bị điện chất lượng cao',
    website: 'https://www.fujielectric.com',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'brand-8',
    name: 'INVT',
    slug: 'invt',
    description: 'INVT (Trung Quốc) - Biến tần chuyên dụng',
    website: 'https://www.invt.com',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// ==================== CATEGORIES ====================
// Structure: Parent Categories (Brands/Serials) → Subcategories (Product Types) → Products
export const MOCK_CATEGORIES: Category[] = [
  // ============ PARENT CATEGORIES (Top Level - Brands/Serials) ============
  {
    id: 'cat-parent-ls',
    name: 'Thiết bị điện LS',
    slug: 'thiet-bi-dien-ls',
    description: 'Công ty Dtech cung cấp các thiết bị điện hạ thế của LS bao gồm:',
    image: MOCK_MEDIA[0],
    parent: undefined, // Top level
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat-parent-mitsubishi',
    name: 'Thiết bị điện Mitsubishi',
    slug: 'thiet-bi-dien-mitsubishi',
    description: 'Công ty Dtech cung cấp các thiết bị điện Mitsubishi bao gồm:',
    image: MOCK_MEDIA[1],
    parent: undefined,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat-parent-schneider',
    name: 'Thiết bị điện Schneider',
    slug: 'thiet-bi-dien-schneider',
    description: 'Công ty Dtech cung cấp các thiết bị điện Schneider Electric bao gồm:',
    image: MOCK_MEDIA[2],
    parent: undefined,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ============ THIẾT BỊ ĐIỆN LS - SUBCATEGORIES ============
  {
    id: 'cat-ls-mccb',
    name: 'MCCB LS - Aptomat khối LS',
    slug: 'mccb-ls',
    description: 'Cầu dao tự động dạng khối LS - MCCB 2P, 3P, 4P từ 15A đến 1600A',
    image: MOCK_MEDIA[0],
    parent: 'cat-parent-ls', // Child of LS
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat-ls-mcb',
    name: 'MCB LS - Aptomat tép LS',
    slug: 'mcb-ls',
    description: 'Cầu dao tự động dạng tép LS - MCB 1P, 2P, 3P, 4P từ 6A đến 125A',
    image: MOCK_MEDIA[0],
    parent: 'cat-parent-ls',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat-ls-contactor',
    name: 'Contactor LS - Khởi động từ LS',
    slug: 'contactor-ls',
    description: 'Khởi động từ LS 3 pha, 4 pha - AC Coil 380V, 220V, 110V từ 6A đến 800A',
    image: MOCK_MEDIA[0],
    parent: 'cat-parent-ls',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat-ls-acb',
    name: 'ACB LS - Máy cắt không khí LS',
    slug: 'acb-ls',
    description: 'Máy cắt không khí LS ACB - Dòng lớn từ 630A đến 6300A',
    image: MOCK_MEDIA[0],
    parent: 'cat-parent-ls',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat-ls-inverter',
    name: 'Biến tần LS',
    slug: 'bien-tan-ls',
    description: 'Biến tần Inverter LS - Điều khiển tốc độ động cơ từ 0.4kW đến 630kW',
    image: MOCK_MEDIA[0],
    parent: 'cat-parent-ls',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat-ls-relay',
    name: 'Rơ le nhiệt LS',
    slug: 'ro-le-nhiet-ls',
    description: 'Rơ le nhiệt bảo vệ quá tải LS - Thermal Relay từ 0.1A đến 800A',
    image: MOCK_MEDIA[0],
    parent: 'cat-parent-ls',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ============ THIẾT BỊ ĐIỆN MITSUBISHI - SUBCATEGORIES ============
  {
    id: 'cat-mitsubishi-inverter',
    name: 'Biến tần Mitsubishi',
    slug: 'bien-tan-mitsubishi',
    description: 'Biến tần Inverter Mitsubishi FR-D, FR-E, FR-A series',
    image: MOCK_MEDIA[1],
    parent: 'cat-parent-mitsubishi',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat-mitsubishi-plc',
    name: 'PLC Mitsubishi',
    slug: 'plc-mitsubishi',
    description: 'PLC Mitsubishi FX, Q series - Điều khiển lập trình',
    image: MOCK_MEDIA[1],
    parent: 'cat-parent-mitsubishi',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat-mitsubishi-servo',
    name: 'Servo Mitsubishi',
    slug: 'servo-mitsubishi',
    description: 'Động cơ Servo Mitsubishi - Điều khiển chính xác cao',
    image: MOCK_MEDIA[1],
    parent: 'cat-parent-mitsubishi',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ============ THIẾT BỊ ĐIỆN SCHNEIDER - SUBCATEGORIES ============
  {
    id: 'cat-schneider-contactor',
    name: 'Contactor Schneider',
    slug: 'contactor-schneider',
    description: 'Khởi động từ Schneider TeSys D, K, F series',
    image: MOCK_MEDIA[2],
    parent: 'cat-parent-schneider',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat-schneider-mccb',
    name: 'MCCB Schneider',
    slug: 'mccb-schneider',
    description: 'Aptomat khối Schneider NSX, EZC series',
    image: MOCK_MEDIA[2],
    parent: 'cat-parent-schneider',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat-schneider-inverter',
    name: 'Biến tần Schneider',
    slug: 'bien-tan-schneider',
    description: 'Biến tần Schneider Altivar series',
    image: MOCK_MEDIA[2],
    parent: 'cat-parent-schneider',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];


// ==================== PRODUCTS ====================
export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'MCCB LS BN630N 3P 630A',
    slug: 'mccb-ls-bn630n-3p-630a',
    code: 'BN630N-630A',
    description: 'Cầu dao tự động (MCCB) LS BN630N 3P 630A - Bảo vệ quá tải, ngắn mạch',
    category: MOCK_CATEGORIES.find(c => c.id === 'cat-ls-mccb'),
    brand: MOCK_BRANDS[0],
    images: [MOCK_MEDIA[0]],
    specifications: [
      { key: 'Dòng định mức', value: '630A' },
      { key: 'Số cực', value: '3P' },
      { key: 'Điện áp', value: '690V AC' },
      { key: 'Công suất cắt', value: '50kA' },
      { key: 'Xuất xứ', value: 'Hàn Quốc' },
    ],
    applications: ['Nhà máy', 'Tòa nhà', 'Dân dụng'],
    priceRange: { min: 2500000, max: 3000000 },
    featured: true,
    status: 'published',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-2',
    name: 'Biến tần Mitsubishi FR-D720S 0.75kW',
    slug: 'bien-tan-mitsubishi-fr-d720s-075kw',
    code: 'FR-D720S-0.75K',
    description: 'Biến tần Mitsubishi FR-D720S 0.75kW - Điều khiển động cơ chính xác',
    category: MOCK_CATEGORIES.find(c => c.id === 'cat-mitsubishi-inverter'),
    brand: MOCK_BRANDS[1],
    images: [MOCK_MEDIA[1]],
    specifications: [
      { key: 'Công suất', value: '0.75kW' },
      { key: 'Điện áp vào', value: '1/3 pha 220V' },
      { key: 'Điện áp ra', value: '3 pha 220V' },
      { key: 'Dòng định mức', value: '4.2A' },
      { key: 'Xuất xứ', value: 'Nhật Bản' },
    ],
    applications: ['Máy bơm', 'Quạt gió', 'Băng tải'],
    priceRange: { min: 3500000, max: 4000000 },
    featured: true,
    status: 'published',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-3',
    name: 'Contactor Schneider LC1D09M7',
    slug: 'contactor-schneider-lc1d09m7',
    code: 'LC1D09M7',
    description: 'Contactor Schneider LC1D09M7 9A 220V - TeSys D',
    category: MOCK_CATEGORIES.find(c => c.id === 'cat-schneider-contactor'),
    brand: MOCK_BRANDS[2],
    images: [MOCK_MEDIA[2]],
    specifications: [
      { key: 'Dòng định mức', value: '9A' },
      { key: 'Điện áp cuộn dây', value: '220V AC' },
      { key: 'Số cực chính', value: '3P' },
      { key: 'Tiếp điểm phụ', value: '1NO + 1NC' },
      { key: 'Xuất xứ', value: 'Pháp' },
    ],
    applications: ['Công nghiệp', 'Hệ thống điều khiển'],
    priceRange: { min: 150000, max: 200000 },
    featured: false,
    status: 'published',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-4',
    name: 'MCB LS BKN 2P 32A',
    slug: 'mcb-ls-bkn-2p-32a',
    code: 'BKN-2P-32A',
    description: 'Cầu dao tự động dạng tép LS BKN 2P 32A - Bảo vệ quá tải, ngắn mạch',
    category: MOCK_CATEGORIES.find(c => c.id === 'cat-ls-mcb'),
    brand: MOCK_BRANDS[0],
    images: [MOCK_MEDIA[0]],
    specifications: [
      { key: 'Dòng định mức', value: '32A' },
      { key: 'Số cực', value: '2P' },
      { key: 'Điện áp', value: '230/400V AC' },
      { key: 'Đặc tính', value: 'C Curve' },
      { key: 'Xuất xứ', value: 'Hàn Quốc'},
    ],
    applications: ['Dân dụng', 'Thương mại', 'Công nghiệp nhẹ'],
    priceRange: { min: 80000, max: 120000 },
    featured: true,
    status: 'published',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-5',
    name: 'Contactor LS MC-40a 3P 40A',
    slug: 'contactor-ls-mc-40a-3p-40a',
    code: 'MC-40a',
    description: 'Khởi động từ LS MC-40a 3P 40A 220V - Metasol series',
    category: MOCK_CATEGORIES.find(c => c.id === 'cat-ls-contactor'),
    brand: MOCK_BRANDS[0],
    images: [MOCK_MEDIA[0]],
    specifications: [
      { key: 'Dòng định mức', value: '40A' },
      { key: 'Điện áp cuộn dây', value: '220V AC' },
      { key: 'Số cực chính', value: '3P' },
      { key: 'Tiếp điểm phụ', value: '1NO + 1NC' },
      { key: 'Xuất xứ', value: 'Hàn Quốc' },
    ],
    applications: ['Động cơ', 'Máy móc công nghiệp'],
    priceRange: { min: 250000, max: 350000 },
    featured: false,
    status: 'published',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];


// ==================== POSTS ====================
export const MOCK_POSTS: Post[] = [
  {
    id: 'post-1',
    title: 'Hướng dẫn chọn MCCB phù hợp cho gia đình',
    slug: 'huong-dan-chon-mccb-phu-hop-cho-gia-dinh',
    excerpt: 'MCCB là gì? Làm thế nào để chọn MCCB phù hợp với công suất điện gia đình? Hãy cùng tìm hiểu trong bài viết này.',
    author: 'Kỹ sư Nguyễn Văn A',
    publishedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), // 5 days ago
    status: 'published',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'post-2',
    title: 'Biến tần là gì? Ứng dụng của biến tần trong công nghiệp',
    slug: 'bien-tan-la-gi-ung-dung-cua-bien-tan-trong-cong-nghiep',
    excerpt: 'Biến tần giúp tiết kiệm điện năng lên đến 30-50%. Tìm hiểu nguyên lý hoạt động và ứng dụng thực tế.',
    author: 'Kỹ sư Trần Thị B',
    publishedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(), // 10 days ago
    status: 'published',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'post-3',
    title: 'So sánh thiết bị điện LS và Schneider',
    slug: 'so-sanh-thiet-bi-dien-ls-va-schneider',
    excerpt: 'LS hay Schneider tốt hơn? Phân tích ưu nhược điểm của từng thương hiệu để lựa chọn phù hợp.',
    author: 'Kỹ sư Lê Văn C',
    publishedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'published',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// ==================== PAGES ====================
export const MOCK_PAGES: Page[] = [
  {
    id: 'page-1',
    title: 'Giới thiệu về DTech Vietnam',
    slug: 'about',
    status: 'published',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'page-2',
    title: 'Chính sách bảo hành',
    slug: 'warranty-policy',
    status: 'published',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'page-3',
    title: 'Hướng dẫn mua hàng',
    slug: 'buying-guide',
    status: 'published',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// ==================== SERIALS ====================
export const MOCK_SERIALS: Serial[] = [
  {
    id: 'serial-1',
    name: 'THIẾT BỊ ĐÓNG CẮT',
    slug: 'thiet-bi-dong-cat',
    description: 'Thiết bị đóng cắt điện công nghiệp từ các thương hiệu hàng đầu: LS, Mitsubishi, Schneider, ABB...',
    categories: MOCK_CATEGORIES.slice(0, 6),
    order: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'serial-2',
    name: 'BIẾN TẦN - KHỞI ĐỘNG MỀM',
    slug: 'bien-tan-khoi-dong-mem',
    description: 'Biến tần và khởi động mềm cho động cơ công nghiệp - Tiết kiệm điện, bảo vệ thiết bị',
    categories: MOCK_CATEGORIES.slice(6, 18),
    order: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'serial-3',
    name: 'THIẾT BỊ TỦ CSPK',
    slug: 'thiet-bi-tu-cspk',
    description: 'Thiết bị tụ bù và bộ điều khiển công suất phản kháng - Cải thiện hệ số cos φ',
    categories: MOCK_CATEGORIES.slice(18, 22),
    order: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// ==================== API RESPONSES ====================
export const MOCK_MEDIA_RESPONSE = {
  docs: MOCK_MEDIA,
  totalDocs: MOCK_MEDIA.length,
  limit: 10,
  totalPages: 1,
  page: 1,
  pagingCounter: 1,
  hasPrevPage: false,
  hasNextPage: false,
  prevPage: null,
  nextPage: null,
};

export const MOCK_BRANDS_RESPONSE = {
  docs: MOCK_BRANDS,
  totalDocs: MOCK_BRANDS.length,
  limit: 10,
  totalPages: 1,
  page: 1,
  pagingCounter: 1,
  hasPrevPage: false,
  hasNextPage: false,
  prevPage: null,
  nextPage: null,
};

export const MOCK_CATEGORIES_RESPONSE = {
  docs: MOCK_CATEGORIES,
  totalDocs: MOCK_CATEGORIES.length,
  limit: 100,
  totalPages: 1,
  page: 1,
  pagingCounter: 1,
  hasPrevPage: false,
  hasNextPage: false,
  prevPage: null,
  nextPage: null,
};

export const MOCK_PRODUCTS_RESPONSE = {
  docs: MOCK_PRODUCTS,
  totalDocs: MOCK_PRODUCTS.length,
  limit: 12,
  totalPages: 1,
  page: 1,
  pagingCounter: 1,
  hasPrevPage: false,
  hasNextPage: false,
  prevPage: null,
  nextPage: null,
};

export const MOCK_POSTS_RESPONSE = {
  docs: MOCK_POSTS,
  totalDocs: MOCK_POSTS.length,
  limit: 10,
  totalPages: 1,
  page: 1,
  pagingCounter: 1,
  hasPrevPage: false,
  hasNextPage: false,
  prevPage: null,
  nextPage: null,
};

export const MOCK_PAGES_RESPONSE = {
  docs: MOCK_PAGES,
  totalDocs: MOCK_PAGES.length,
  limit: 10,
  totalPages: 1,
  page: 1,
  pagingCounter: 1,
  hasPrevPage: false,
  hasNextPage: false,
  prevPage: null,
  nextPage: null,
};

export const MOCK_SERIALS_RESPONSE = {
  docs: MOCK_SERIALS,
  totalDocs: MOCK_SERIALS.length,
  limit: 10,
  totalPages: 1,
  page: 1,
  pagingCounter: 1,
  hasPrevPage: false,
  hasNextPage: false,
  prevPage: null,
  nextPage: null,
};
